services:
  fxserver-thrasherverse:
    image: lilthrasher/fxserver:latest
    container_name: fxserver-thrasherverse
    restart: unless-stopped
    ports:
      - 30120:30120/tcp
      - 30120:30120/udp
      - 40120:40120/tcp # txAdmin
    volumes:
      - ${SERVER_DATA}:/opt/fxserver/txData

  mariadb-fxserver:
    image: mariadb:latest
    container_name: mariadb-fxserver
    restart: unless-stopped
    volumes:
      - mariadb-fxserver:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

volumes:
  mariadb-fxserver:
    external: true